### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by jpeterson** [Esri/calcite-react#17]
## Calcite Web
http://esri.github.io/calcite-web/documentation/components/#selects

## Tasks
- [x] Implement Component
- [x] Write Story
- [x] Fix Keyboard Nav
- [x] Default Button Input instead of select/input[text]

## Synthetic Events
TBD...

## Props
- [x] fullWidth
- [x] native (Or do we just pass in a `select` element?)
  - They can just use the styled component for that stuff...
